### ISSUE TITLE
Remove auto-unwrapping using propName?

### ISSUE THREAD

**Issue by pselden** [sonaye/mobx-apollo#10]
There's this line here: https://github.com/sonaye/mobx-apollo/blob/master/src/index.js#L11 which unwraps the propName inside of the data object, if and only if there is only one key inside of it. To me, this is not very intuitive and has caused me a few headaches trying to get things to work where I named my class property something other than what my graphql returns. Could you consider removing that feature and just exposing the data directly?

```js
const ORGS_QUERY = gql`{
   organizations {
     pageInfo {
       hasMore
     }    
     edges {
       id
      name
    }
   }
}`;


class OrganizationsStore {
   constructor() {
     query(this, 'organizationsQuery', { client: client, query: ORGS_QUERY });
   }

   @computed
   get organizations() {
     return this.organizationsQuery.data.organizations.edges; // woops, data is undefined because internally it's setting data= data.organizationsQuery, which doesn't exist in my schema
   }
}
```

**Comment by sonaye** [comment]
Try @0.0.16, just pushed a patch, it no longer make any assumptions about the naming in your schema. I would disagree that it is non-intuitive, I think it make since that if there was only one result we would have one node matching to it, this prevent bad syntax like `postsStore.allPosts.data.allPosts`, typically this is how you would do it. It was only non-intuitive in this case because it was a bug :) This why we have the issues tracker, to fine tune code and support as many edge cases as possible.

**Comment by sonaye** [comment]
Your computed should look like this now:
```javascript
@computed get organizations() {
 return this.organizationsQuery.data && this.organizationsQuery.data.edges;
}
```

**Comment by pselden** [comment]
Hey that's awesome, thanks a lot for the fast response!

**Comment by pselden** [comment]
Sorry to bring this back up again, but I did notice that there is a difference now between queries that return one value vs queries that return multiple values that just bit me because I was expecting it to be the data object instead.

https://github.com/sonaye/mobx-apollo/blob/master/src/index.js#L11

Example:

```gql
query {
   options {
      id,
      name
   }
}
```

```js
@computed get options() {
   return this.optionsQuery.data || []; // this doesn't actually work, since the first time it's resolved it's an ObservableObjectAdministration from mobx.
}
```

If there was no auto-unwrapping it would look like:

```js
@computed get options() {
   return this.optionsQuery.data.options || []; // hurray, this works!
}
```

Additionally, it's not not clear to me that the data object differs if and only if there is one key (unless I read the code).

```gql
query {
   options {
      id
      name
   }

   anotherObject { }
}
```

Now all of a sudden my second example works... but now if I refactor and pull anotherObject out of the query, it's a breaking change to my computed that doesn't even deal with anotherObject!

I realize this is breaking change so shouldn't be taken lightly -- but just wanted to draw attention to it in case other people feel the same way.

**Comment by pselden** [comment]
https://github.com/sonaye/mobx-apollo/issues/10#issuecomment-342543738

I'm actually thinking this is two separate issues: 

1) That the data property "changes shape" from an ObservableObjectAdministration to the actual result after next is called  again -- possibly just a bug fix.

2) That multiple keys in a query are handled differently -- a breaking change for sure.

**Comment by sonaye** [comment]
Can you please visit this [answer](https://stackoverflow.com/questions/43166411/mobx-returning-observableobjectadministration-instead-of-my-object) and see if it resolves things for you? Ref is [here](https://mobx.js.org/refguide/tojson.html).

**Comment by pselden** [comment]
It still appears that they are different objects.

https://github.com/pselden/mobx-apollo-test

You can see it switches from an object (probably the actual apollo query data object) to an array after the data resolves.

**Comment by sonaye** [comment]
Something is very strange here, not sure why we need `toJS`, we didn't before, I will do more investigation on this later on. Meanwhile, this solves both issues mentioned.

```javascript
const gql = require('graphql-tag');
const { ApolloClient, createNetworkInterface } = require('apollo-client');
const { autorun, extendObservable, toJS } = require('mobx');
const { query } = require('mobx-apollo');

global.fetch = require('node-fetch');

const client = new ApolloClient({
  networkInterface: createNetworkInterface({
    uri: 'https://api.graph.cool/simple/v1/cj7c7kt9m08oe0198x4sk8zgy',
    dataIdFromObject: o => o.id
  })
});

const allPosts = gql`
  {
    allPosts {
      id
      title
    }
  }
`;

class PostsStore {
  constructor() {
    query(this, '_allPosts', { client, query: allPosts });

    extendObservable(this, {
      postId: 'cj7c8rb0x1ndu01842w34gxby',
      get allPosts() {
        return toJS(this._allPosts);
      },
      get posts() {
        const data = this.allPosts && this.allPosts.data;
        return data.length ? data : [];
      },
      get postNames() {
        const data = this.allPosts && this.allPosts.data;
        return data.length ? this.allPosts.data.map(post => post.title) : [];
      },
      get currentPost() {
        const data = this.allPosts && this.allPosts.data;
        return data.length
          ? this.allPosts.data.filter(post => post.id === this.postId)[0]
          : {};
      }
    });
  }

  setCurrentPost(postId) {
    this.postId = postId;
  }
}

const postsStore = new PostsStore();

autorun(
  () =>
    postsStore.allPosts.error &&
    console.error('error', postsStore.allPosts.error.message)
);

autorun(() => console.log('loading', postsStore.allPosts.loading));

autorun(() => console.log('posts', postsStore.posts));
autorun(() => console.log('post names', postsStore.postNames));
autorun(() => console.log('current post', postsStore.currentPost));

setTimeout(() => postsStore.setCurrentPost('cj7c8r8cp1m0r01150rw0w8co'), 1000);
```

**Comment by sonaye** [comment]
Tested with:
```
  "dependencies": {
    "apollo-client": "1.9.3",
    "graphql-tag": "2.5.0",
    "mobx": "3.3.1",
    "mobx-apollo": "0.0.16",
    "node-fetch": "1.7.3"
  }
```

**Comment by sonaye** [comment]
Ah, one more thing, to change variables in a query you should do something like
```javascript
store.query.ref.setVariables({ var: val });
```

**Comment by pselden** [comment]
https://github.com/sonaye/mobx-apollo/issues/10#issuecomment-343428858 -- yeah, sorry -- this was a leftover for when I was attempting to make it automatically respond to variable changes.

**Comment by pselden** [comment]
OK I tracked down what I think the issue is:

query.currentResult() returns something like { data: {}, loading: true} -- this is not put through the same data transformation processing as the subscription is: https://github.com/sonaye/mobx-apollo/blob/master/src/index.js#L4, so the first time we run the query we get {} instead of undefined. When data actually shows up it will be sent through next.

Unfortunately there is no good way to fix this and still keep the semantics of "result with one key changes the data property".  I still think that design choice is confusing, especially now that some of the other apollo attributes are exposed directly -- I think we should just be returning the apollo "data" directly and be done with it.

Also, while the code posted does work, it's only because it's checking the .length property (which doesn't exist on the object) -- it's not like it's a real array.

**Comment by sonaye** [comment]
> Also, while the code posted does work, it's only because it's checking the .length property (which doesn't exist on the object) -- it's not like it's a real array.

You would always have to do some custom checking if you want a consistent type.

I think the `toJS` part is related to Node (any none React tailored env in general), my guess is that `mobx-react` handles that internally, so typically we don't need `toJS`.
