### ISSUE TITLE
Nested props are not reactive

### ISSUE THREAD

**Issue by dehypnosis** [sonaye/mobx-apollo#12]
Yeah, thank you for your hard work,
but i noticed that nested props are not reative.

in graphql type nesting is very common but currently mobx-apollo seems not to track nested props.

did I use this wrong way? or really it is not supported?

**Comment by sonaye** [comment]
Care to offer some code that illustrate the issue better?

**Comment by dehypnosis** [comment]
Yes, in abstracto, I have a type User, and User can have type File as avatar
```js
User {
  id: Int
  name: String
  avatar: File
}

File {
  id: Int
  url: String
}
```

So when my store state (with graphql from mobx-apollo) can be
```js
@observable user = {
 id: 1,
 __type: 'User',
 name: '..',
 avatar: {
  id: 1,
  __type: 'File',
  url: '...'
 }
}
```

when i update state as `user.avatar = null` or `user.avatar = otherFile`, it works well.
But when i update user.avatar.url, it not works reactively.

Thanks

**Comment by dehypnosis** [comment]
oops give me a minute, seems like not related to this library..
will comment if found certain issue. Sorry for annoying you

**Comment by sonaye** [comment]
Not a problem, let me know if you need any help.

You shouldn't update the state this way, you shouldn't modify the `mobx-apollo` reference, that's for sure. You should derive the new state from the fetched state with a mobx `@computed` then you can modify it, see the store example [here](https://github.com/sonaye/mobx-apollo#example).

To what other library is this related may I ask?

**Comment by dehypnosis** [comment]
Not a certain library, it was my mistake from design.
I was bit confused about Observable of mobx between cache and watchedQuery of apollo.
sorry for the happening, i apprectiate to your concern.
