### ISSUE TITLE
How to update cache after mutation with using refetchQueries?

### ISSUE THREAD

**Issue by pratikt-cuelogic** [sonaye/mobx-apollo#15]
How to update cache after mutation with using refetchQueries

**Comment by sonaye** [comment]
Hi, I didn't understand your question, we do use `refetchQueries` to update the cache after a mutation. Take a look at the [example](https://github.com/sonaye/mobx-apollo#example).

**Comment by sonaye** [comment]
Based on your reply in #14 I think you are looking for subscriptions, I posted a solution there. Please reopen if that doesn't fix the issue you are facing.

**Comment by pratikt-cuelogic** [comment]
thanks (y)
