### ISSUE TITLE
Support MobX 4

### ISSUE THREAD

**Issue by ryanking1809** [sonaye/mobx-apollo#16]
Just testing this out but I'm getting the following error:
`TypeError: Cannot define property __mobxDidRunLazyInitializers, object is not extensible`

Looks like this line is causing the issue: 
`const observableQuery = observable(query.currentResult());`

Any ideas what's going on here?

My code looks like based on the example in the docs:
```on
const allTasksQuery = gql`
  {
    allTasks(orderBy: createdAt_DESC) {
      id
      label
    }
  }
`;

const httpLink = new HttpLink({ uri: 'https://api.graph.cool/simple/v1/xxx' })

const client = new ApolloClient({
  link: httpLink,
  cache: new InMemoryCache()
})

console.log('allTasks', graphql({ client, query: allTasksQuery }))
```

**Comment by ryanking1809** [comment]
see: https://codesandbox.io/s/2or57135vp

**Comment by ryanking1809** [comment]
I need to look into it further but it seems to work with `"mobx": "3.6.2", "mobx-react": "4.4.0"`

**Comment by sonaye** [comment]
Yes, MobX 4 breaks the current API which is based on MobX 3.

**Comment by sonaye** [comment]
Were you able to test after teh fix in https://github.com/mobxjs/mobx/issues/1404?

**Comment by ryanking1809** [comment]
Yes, appears to be working! Thanks for your help.
