### ISSUE TITLE
Skipping queries

### ISSUE THREAD

**Issue by ammichael** [sonaye/mobx-apollo#18]
Hi there,

First thanks for the lib. I've been using it for a while and it works pretty well (: 

I'm having problems skipping the operation when conditions are not met. Basically, putting the 'skip' property doesn't affect at all.

```
    return graphql({
      client,
      query,
      skip: true,
      variables: {
        accounts: this.accounts,
      },
      fetchPolicy: 'cache-and-network',
    });
```

I've also tried putting skip inside 'options' property, but doesn't work as well.
What am I missing here?!

Thanks!

**Comment by sonaye** [comment]
Hello,

I don't see a skip option available in the Apollo client API reference, and particularly in the method used with this library [watchQuery](https://www.apollographql.com/docs/react/api/apollo-client.html#ApolloClient.watchQuery). Hence, passing a skip option has no effects.

What are you trying to do? and what are the conditions that should be met?
