### ISSUE TITLE
Question regarding implementation

### ISSUE THREAD

**Issue by mweststrate** [sonaye/mobx-apollo#2]
Hey @sonaye!

Really cool package, exactly what `fromResource` was intended to do. 

Small question out of curiosity about this line: `sink(observable(multiple === true ? data : data[prop]));`. Why is the data passed through `observable`? With my limited knowledge of apollo; the data received here won't change directly if I am correct, so skipping `observable` will result in the same behavior?

Thanks!

**Comment by sonaye** [comment]
Hey! thanks for taking the time to go through the code, much appreciated.

Indeed you are correct, good catch! removing `observable` results the exact same behavior. I think we are used to using `computed` with `observable` that's all, as a matter of fact, I can't recall any cases where I used `computed` alone.

I actually used your snippet here https://github.com/apollographql/apollo-client/issues/503#issuecomment-241101379 as the reference for this implementation, in which you also used `observable`. Did you have something in mind back then?

I will be pushing a new version that addresses this point.

**Comment by mweststrate** [comment]
Nope, that was probably an oversight from my side :)

Op di 1 aug. 2017 om 22:51 schreef sonaye <notifications@github.com>:

**Comment by sonaye** [comment]
Do you think it would be of any value to add a `@mutation` utility that wraps a mobx action?

```javascript
@mutation createPost = title => { client, mutation, variables: { title } };
// instead of (currently)
@action createPost = title => client.mutate({ mutation, variables: { title } });
// not sure if @action is even needed here
```

I actually tried to implement it just to have a better understanding of how decorators work, but failed to do so, created #1 to remind myself that I should tackle this again at some point.

**Comment by mweststrate** [comment]
That is hard for me to judge :) Decorators are fun and horrible at the same
time. You want might to play with passing data to decorators (I saw you now
to took it from the initialValue, but that does not always work as expected
with TS versus Babel, or with inheritance. Passing data is basically
wrapping an additional function around it: `function query(options) {
return function (target, prop, descriptor) { ... original implementation,
but now access options from the closure } }`

Op di 1 aug. 2017 om 23:20 schreef sonaye <notifications@github.com>:

**Comment by sonaye** [comment]
That crossed my mind, passing the data in the decorator itself I mean, and yes I actually was very confused at the beginning by the initializer, all the references I found were mentioning `descriptor.value` and not the initializer. Not sure why the decorators proposal in particular has all this fuzz around it, it adds a great value to the language, provided that its implementation is fine tuned and standardized.
