### ISSUE TITLE
Queries with variables

### ISSUE THREAD

**Issue by ikatun** [sonaye/mobx-apollo#20]
Is there a way for react component to pass variables to observable field in a store?

I can see in your examples that all queries are either without variables or variables are passed from the store itself.

**Comment by sonaye** [comment]
You can always access the observable reference (inside or outside the store):

```js
postsStore.allPosts.ref.setVariables({ .. });
```

**Comment by ikatun** [comment]
Thank you for the quick reply :)

That's great if I want to change the result of a previously executed query, for paging or something like that.

But if I were to have a posts query which is reused in different components with different values for variables? There wouldn't be a way to use single store field for that query? I'd have to use two fields which use same query with different variables?

**Comment by sonaye** [comment]
Yes, you'd have to use multiple instances for that, if the variables change, the observable itself changes (they are not the same query, technically you are not "reusing").

What you can do is create a factory in your store for the queries, something like:

```js
class Store {
  createQuery = (name, variables) => {
    this[name] = graphql({ variables, .. });
  }
}

createQuery('foo', { filter: 'bar' });
createQuery('lorem', { filter: 'ipsum' });
```

**Comment by ikatun** [comment]
If I were to use the factory, would something like this work and cause the components to properly rerender on query refetch?
```
class Store {
  createQuery = (name, variables) => {
    this[name] = graphql({ variables, .. });
  }
  foo = variables => this[hash('foo', variables)] || this.createQuery(hash('foo', variables), { variables });
}

// component1 render:
const { data, loading } = store.foo({ olderThan: 'yesterday' })

// component2 render:
const { data, loading } = store.foo({ olderThan: 'last-week' })
```

**Comment by sonaye** [comment]
I would invoke `store.foo({ olderThan: '..' })` once in `componentDidMount` and avoid hashing, but your approach looks fine, I don't see a reason why it wouldn't work.

**Comment by ikatun** [comment]
Just a conclusion for this issue. I've tried this approach and it works great for queries with variables.
@sonaye do you think this functionality could be integrated with the library itself? Or do you want to keep it as simple as possible?

**Comment by sonaye** [comment]
The goal of this package is to provide a very thin layer that helps getting the two sides (Apollo + MobX) running together. I still think the time from zero to hello-world GraphQL is way to complex (just take a look at the examples in the readme, it's too much), I don't want to add any extra layers of complexity to it at this stage.

Unless there is a solid reason to cover an edge case I would be very hesitant to support it. An example of an edge case that was supported is the `.ref` extensions that gives you access to the observable, not only there is good use for it, but it also flexible enough to cover up a wide variety of other typical use cases.
