### ISSUE TITLE
Support MobX 5

### ISSUE THREAD

**Issue by pratikt-cuelogic** [sonaye/mobx-apollo#22]

**Comment by sonaye** [comment]
Not sure about 5, but it works with 4.

**Comment by pratikt-cuelogic** [comment]
thanks for the update @sonaye , just tried mobx 5, it doesn't work.
any plans for extending support for mobx 5 ?

**Comment by sonaye** [comment]
No plans unfortunately at the moment as I don't have the capacity to do so. Happy to merge any PRs that add support for it.
