### ISSUE TITLE
React to variable changes

### ISSUE THREAD

**Issue by bkniffler** [sonaye/mobx-apollo#6]
Hey, 
It would be super cool if it would subscribe to changes of variables, so refetch occurs automatically whenever variable changes

**Comment by sonaye** [comment]
There are multiple ways to achieve that currently I believe.

- Manually refetching specific queries after mutation `client.mutate({ refetchQueries: [{ query }] })`.
- Using polling, `client.query({ pollInterval: 30000 })`.
- Using subscriptions. I haven't tested them yet but I think they should work out of the box with this package. Instead of passing the default apollo client we utilize the enhanced one (with subscriptions), and pass matching query. I will test this soon, perhaps you could give it a shot and let me know about it.

With the exception of subscriptions (haven't tested them yet), the rest of the options do work. I personally manually refetch queries with optimistic ui.

**Comment by bkniffler** [comment]
Thanks for taking the time to answer. I think I didn't make myself clear enough. What I'd like to achieve ist not refetching after mutation or via pulling/subscriptions, but via change of variables. Lets say this.users is an observable:

```
query(this, 'list', {
      client: this.client,
      query: gqlList,
      variables: {
        userIds: this.users,
      },
      onError: error => console.log(error),
    });
```

Would be cool if whenever this.users is changed, the query would refetch.

**Comment by sonaye** [comment]
I think you can achieve that with [autorun()](https://mobx.js.org/refguide/autorun.html), something like:
```javascript
const client = new ApolloClient();

const listQuery = gql``;

class Store() {
  constructor() {
    query(this, 'list', { client, query: listQuery });

    extendObservable(this, { users: [] });
  }
}

const store = new Store();

autorun(() => {
  console.log(store.users); // we are telling autorun() to watch store.users
  client.query({ query: listQuery });
});
```

**Comment by bkniffler** [comment]
That works well, I appreciate your help!
Maybe you could add it to your library, something like
```
if (typeof variables === 'function') {
    const ref = extendObservable(obj, {
      [privateName]: queryToObservable(client.watchQuery({ ...options, variables: variables() }), {
        onError,
        onFetch,
        prop,
      }),
      [prop]: computed(() => obj[privateName].current()),
    });
    reaction(variables, (variables) => {
      client.query({ ...options, variables });
    });
    if (decorated) {
      return ref;
    }
  }
```

This would make something like that possible:
```
query(this, 'list', {
      client: this.client,
      query: gqlList,
      variables: () => ({
        userIds: this.users.map(x => x.id),
      }),
      onError: error => console.log(error),
    });
```

**Comment by sonaye** [comment]
Glad it works. At the moment, the objective is to enable/expose the bare minimum functionality needed to get mobx and apollo working nicely together, I don't want to overwhelm the package with extra methods for custom scenarios. 

Good call with using `reaction()` instead! didn't know it existed.

**Comment by sonaye** [comment]
Just pushed a new version where you can import `queryToObservable` directly from the package instead of rewriting it, this should make extending the package with custom methods easier for you.

**Comment by pselden** [comment]
I'm having a little trouble figuring out how to use this. Do i pass it the result of query()?

**Comment by sonaye** [comment]
@pselden You don't need to pass anything to `query()`, use it regularly.

This is a mobx case, where you have an observable in your store and a function outside it that executes whenever that observable changes, for that we can use [autorun](https://mobx.js.org/refguide/autorun.html).

Let's say that we have two stores and we want them to be in sync for some reason (bad design).

```javascript
const store1 = new class { foo = 123; }();
const store2 = new class { bar = 123; }();

autorun(() => (store1.foo = store2.bar)); // when store2.bar changes, sync store1.foo with it
autorun(() => (store2.bar = store1.foo)); // when store1.foo changes, sync store2.bar with it

store1.foo = 0; console.log(store1.foo, store2.bar); // 0, 0
store1.foo = 1; console.log(store1.foo, store2.bar); // 1, 1

store2.bar = 0; console.log(store1.foo, store2.bar); // 0, 0
store2.bar = 1; console.log(store1.foo, store2.bar); // 1, 1
```

Now `store1.foo` and `store2.bar` will always have the same value. Autorun checks if the observables referenced within it have changed, and if so, it executes itself.

**Comment by sonaye** [comment]
> How would I use the new method to react to variable changes?

Exactly like this https://github.com/sonaye/mobx-apollo/issues/6#issuecomment-323334601, and there are no new methods here.

**Comment by pselden** [comment]
Hm... I'm having trouble getting the actual query to refresh when the variables change.

```
class OrganizationsStore {
  constructor() {
    extendObservable(this, { sort: { columnId: 'id', direction: 'asc' } });

    query(this, 'organizations', {
      client: client,
      query: ORGANIZATIONS_QUERY,
      variables: this.organizationsQueryVariables
    });

    autorun(() => {
      coreApiClient.query({
        query: ORGANIZATIONS_QUERY,
        variables: this.organizationsQueryVariables
      });
    });
  }

  @computed
  get organizationsQueryVariables() {
    const { columnId, direction } = this.sort;
    const sort = {
      field: columnId,
      descending: direction === 'desc'
    };

    return {
      sort: [sort]
    };
  }
}

const store = new OrganizationsStore();
autorun(() => {
  console.log(store.organizations);
});
```
I get the initial set of data, then when I change sort I see a new query being made in the network tab, but I don't see my log of the store.organizations being updated. Do i need to do something special to sync the query in the autorun back to my query() variable?

**Comment by sonaye** [comment]
`autorun()` should be outside the store.

**Comment by pselden** [comment]
Not sure that matters -- I moved it outside but still only saw my log happen once (graphql queries do fire though)

**Comment by sonaye** [comment]
You need to include the variable that `autorun()` should listen to.
```diff
autorun(() => {
+ store.foo; // or const foo = store.foo; or console.log(store.foo); or any dummy command that references store.foo
  client.query({
    query: ORGANIZATIONS_QUERY,
    variables: store.organizationsQueryVariables
  });
});
```
Autorun will execute if and only if store.foo changes.

**Comment by pselden** [comment]
The autorun is triggering (because the variable is firing -- it's just that the data doesn't get refreshed inside the internal watchQuery just from an external client.query).

I made some monkeypatches in the code and looks like I have to keep ahold of the query object from watchQuery and actually call refetch(). Does that sound right? In which case I can't achieve it with the current library.  @bkniffler -- how did you get it to work with the current lib?

**Comment by sonaye** [comment]
If the data is not refreshing, this means that either no new data was added properly, or that `autorun()` is not listening to what it should be listening to. We call `client.query()` to force update the cache of the apollo client, that's our `refetch()`.

> because the variable is firing

How exactly? I don't see you calling any new sort actions in your code.

Plus, I just noticed `variables: this.organizationsQueryVariables`, which are obtained through a computed value, you cannot have dynamic values in your `query()` variables, it will be called one time only at the beginning, and then whenever the apollo cache updates for some reason (force refetch) -from another source in your app-, those changes would be reflected.

I can see that you are trying to implement a data sorting mechanism, this is not the best way to go about it. Try [sortBy()](https://lodash.com/docs/4.17.4#sortBy).

**Comment by sonaye** [comment]
On a second thought, I think you can achieve what you are looking for also by overwriting the current subscription.

```javascript
autorun(() =>
  query(store, 'organizations', {
    client,
    query: ORGANIZATIONS_QUERY,
    variables: store.organizationsQueryVariables
  })
);
```

Try it and let me know if it works.

**Comment by bkniffler** [comment]
tbh I opted-out by copying this libraries code since its fairly minimal and changed the code as shown in my fifth comment (just before closing the issue), its been working great!

**Comment by sonaye** [comment]
You can now update the variables of the query, using `postsStore.allPosts.ref.setVariables()`.

Here is a pagination example:
```javascript
@query
allPosts = {
  client,
  query: allPosts,
  variables: { first: 10, skip: 0 } // increments of 10 records
};

loadMore = () =>
  this.allPosts.ref.fetchMore({
    variables: { skip: this.allPosts.data.length },
    updateQuery: (previousResult, { fetchMoreResult }) => ({
      allPosts: [...previousResult.allPosts, ...fetchMoreResult.allPosts]
    })
  });
```

**Comment by sonaye** [comment]
@pselden You can take a look at the [docs](http://dev.apollodata.com/core/apollo-client-api.html#ObservableQuery.setVariables), it's pretty straight forward now.
