### ISSUE TITLE
Passing variables to query using query  decorator

### ISSUE THREAD

**Issue by arturkasprzyk** [sonaye/mobx-apollo#9]
Hi,
I have a problem with variables stored as observables in my store. There is a problem with context using 'this' when dealing with '@query' decorator. This is not referring to a class, but to an object instead. When I'm using 'query' in a constructor, everything works as expected however :)

Simple example below:

`  @query
  repositories = {
    ...options,
    query: commits,
    variables: {
      startDate: this.startDate,
    },
  }`

**Comment by sonaye** [comment]
Hey! This behavior is expected, scoping within a constructor is needed for such a case. You can only reference class fields within class methods (scoped functions).
```diff
class {
  foo = 123;
- bar = this.foo; // throws
+ constructor() {
+   this.bar = this.foo; // valid
+ }
}
```

**Comment by sonaye** [comment]
You can also do:
```javascript
@query repositories = { ...options, query: commits }

constructor() {
  this.repositories.ref.setVariables({ startDate: this.startDate });
}
```

Provided that startDate is optional in your graphql schema. I don't recommend it though, because it will result two network calls.

**Comment by arturkasprzyk** [comment]
Thanks for the response! I'll try solution with refs :)

**Comment by sonaye** [comment]
@arturkasprzyk I recommend that you use it within your constructor (without decorators).
